# Binance Live Data Collector Configuration

app:
  name: "binance-live-collector"
  environment: "development"
  log_level: "info"

binance:
  api_url: "https://api.binance.com"
  ws_url: "wss://stream.binance.com:9443"
  # Rate limits per minute
  rest_rate_limit: 1200
  # Kline intervals to collect (1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M)
  kline_intervals:
    - "1m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"

database:
  host: "timescaledb"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "postgres"
  ssl_mode: "disable"
  max_connections: 300
  max_idle_connections: 100
  connection_max_lifetime: 300 # seconds

redis:
  host: "dragonfly"
  port: 6379
  password: "password"
  db: 0
  pool_size: 10
  # TTL for live data in seconds
  live_data_ttl: 60

sync:
  # When service restarts, sync missing data
  enabled: true
  # Maximum hours to sync backwards
  max_sync_hours: 24
  # Batch size for historical data fetching (reduced to avoid large transactions)
  batch_size: 200
  # Concurrent workers for syncing (reduced to avoid connection pool exhaustion)
  workers: 10

stream:
  # Reconnect settings for WebSocket
  reconnect_delay: 5 # seconds
  max_reconnect_attempts: 10
  ping_interval: 30 # seconds
  # Buffer size for channels
  channel_buffer_size: 1000
