// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type DepthSnapshot struct {
	ID           int64  `db:"id" json:"id"`
	Symbol       string `db:"symbol" json:"symbol"`
	Timestamp    int64  `db:"timestamp" json:"timestamp"`
	LastUpdateID int64  `db:"last_update_id" json:"last_update_id"`
	Bids         []byte `db:"bids" json:"bids"`
	Asks         []byte `db:"asks" json:"asks"`
	CreatedAt    int64  `db:"created_at" json:"created_at"`
}

type Kline struct {
	Symbol              string  `db:"symbol" json:"symbol"`
	Interval            string  `db:"interval" json:"interval"`
	OpenTime            int64   `db:"open_time" json:"open_time"`
	CloseTime           int64   `db:"close_time" json:"close_time"`
	OpenPrice           float64 `db:"open_price" json:"open_price"`
	HighPrice           float64 `db:"high_price" json:"high_price"`
	LowPrice            float64 `db:"low_price" json:"low_price"`
	ClosePrice          float64 `db:"close_price" json:"close_price"`
	Volume              float64 `db:"volume" json:"volume"`
	QuoteVolume         float64 `db:"quote_volume" json:"quote_volume"`
	TradesCount         int32   `db:"trades_count" json:"trades_count"`
	TakerBuyVolume      float64 `db:"taker_buy_volume" json:"taker_buy_volume"`
	TakerBuyQuoteVolume float64 `db:"taker_buy_quote_volume" json:"taker_buy_quote_volume"`
	CreatedAt           int64   `db:"created_at" json:"created_at"`
}

type Symbol struct {
	ID         int32  `db:"id" json:"id"`
	Symbol     string `db:"symbol" json:"symbol"`
	BaseAsset  string `db:"base_asset" json:"base_asset"`
	QuoteAsset string `db:"quote_asset" json:"quote_asset"`
	Status     string `db:"status" json:"status"`
	IsActive   bool   `db:"is_active" json:"is_active"`
	CreatedAt  int64  `db:"created_at" json:"created_at"`
	UpdatedAt  int64  `db:"updated_at" json:"updated_at"`
}

type SyncStatus struct {
	Symbol       string         `db:"symbol" json:"symbol"`
	DataType     string         `db:"data_type" json:"data_type"`
	Interval     sql.NullString `db:"interval" json:"interval"`
	LastSyncTime int64          `db:"last_sync_time" json:"last_sync_time"`
	LastDataTime int64          `db:"last_data_time" json:"last_data_time"`
	Status       string         `db:"status" json:"status"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}

type Ticker struct {
	Symbol                string          `db:"symbol" json:"symbol"`
	Timestamp             int64           `db:"timestamp" json:"timestamp"`
	Price                 float64         `db:"price" json:"price"`
	BidPrice              sql.NullFloat64 `db:"bid_price" json:"bid_price"`
	BidQty                sql.NullFloat64 `db:"bid_qty" json:"bid_qty"`
	AskPrice              sql.NullFloat64 `db:"ask_price" json:"ask_price"`
	AskQty                sql.NullFloat64 `db:"ask_qty" json:"ask_qty"`
	Volume24h             sql.NullFloat64 `db:"volume_24h" json:"volume_24h"`
	QuoteVolume24h        sql.NullFloat64 `db:"quote_volume_24h" json:"quote_volume_24h"`
	PriceChange24h        sql.NullFloat64 `db:"price_change_24h" json:"price_change_24h"`
	PriceChangePercent24h sql.NullFloat64 `db:"price_change_percent_24h" json:"price_change_percent_24h"`
	High24h               sql.NullFloat64 `db:"high_24h" json:"high_24h"`
	Low24h                sql.NullFloat64 `db:"low_24h" json:"low_24h"`
	TradesCount24h        sql.NullInt32   `db:"trades_count_24h" json:"trades_count_24h"`
	CreatedAt             int64           `db:"created_at" json:"created_at"`
}

type Trade struct {
	ID            int64   `db:"id" json:"id"`
	Symbol        string  `db:"symbol" json:"symbol"`
	TradeID       int64   `db:"trade_id" json:"trade_id"`
	Timestamp     int64   `db:"timestamp" json:"timestamp"`
	Price         float64 `db:"price" json:"price"`
	Quantity      float64 `db:"quantity" json:"quantity"`
	QuoteQuantity float64 `db:"quote_quantity" json:"quote_quantity"`
	IsBuyerMaker  bool    `db:"is_buyer_maker" json:"is_buyer_maker"`
	CreatedAt     int64   `db:"created_at" json:"created_at"`
}
