// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteOldDepthSnapshots(ctx context.Context, timestamp int64) error
	DeleteOldKlines(ctx context.Context, openTime int64) error
	DeleteOldTickers(ctx context.Context, timestamp int64) error
	DeleteOldTrades(ctx context.Context, timestamp int64) error
	DeleteSymbol(ctx context.Context, symbol string) error
	DeleteSyncStatus(ctx context.Context, arg DeleteSyncStatusParams) error
	GetActiveSymbols(ctx context.Context) ([]Symbol, error)
	GetAllLatestTickers(ctx context.Context) ([]Ticker, error)
	GetAllSymbols(ctx context.Context) ([]Symbol, error)
	GetAllSyncStatuses(ctx context.Context) ([]SyncStatus, error)
	GetDepthSnapshotsByTimeRange(ctx context.Context, arg GetDepthSnapshotsByTimeRangeParams) ([]DepthSnapshot, error)
	GetKlinesByTimeRange(ctx context.Context, arg GetKlinesByTimeRangeParams) ([]Kline, error)
	GetLastKline(ctx context.Context, arg GetLastKlineParams) (Kline, error)
	GetLatestDepthSnapshot(ctx context.Context, symbol string) (DepthSnapshot, error)
	GetLatestKlines(ctx context.Context, arg GetLatestKlinesParams) ([]Kline, error)
	GetLatestTicker(ctx context.Context, symbol string) (Ticker, error)
	GetLatestTrades(ctx context.Context, arg GetLatestTradesParams) ([]Trade, error)
	GetSymbolByName(ctx context.Context, symbol string) (Symbol, error)
	GetSyncStatus(ctx context.Context, arg GetSyncStatusParams) (SyncStatus, error)
	GetSyncStatusesBySymbol(ctx context.Context, symbol string) ([]SyncStatus, error)
	GetTickersByTimeRange(ctx context.Context, arg GetTickersByTimeRangeParams) ([]Ticker, error)
	GetTradesByTimeRange(ctx context.Context, arg GetTradesByTimeRangeParams) ([]Trade, error)
	InsertDepthSnapshot(ctx context.Context, arg InsertDepthSnapshotParams) (InsertDepthSnapshotRow, error)
	InsertKline(ctx context.Context, arg InsertKlineParams) error
	InsertTicker(ctx context.Context, arg InsertTickerParams) error
	InsertTrade(ctx context.Context, arg InsertTradeParams) (InsertTradeRow, error)
	UpdateLastDataTime(ctx context.Context, arg UpdateLastDataTimeParams) error
	UpdateSymbolStatus(ctx context.Context, arg UpdateSymbolStatusParams) error
	UpsertSymbol(ctx context.Context, arg UpsertSymbolParams) (UpsertSymbolRow, error)
	UpsertSyncStatus(ctx context.Context, arg UpsertSyncStatusParams) error
}

var _ Querier = (*Queries)(nil)
